# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Gravity Magazine
tagline:          "Brandeis' Only Humor Magazine"
description:      ''
url:              GravityMagazine.org

author:
  name:           'David Barsky'
  url:            https://twitter.com/barskles

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/davidbarsky/
